# 配置端口
server:
  port: 8080

# dubbo 配置
dubbo:
  application:
    name: dubbo-consumer
  registry:
    # 修改为自己的ip
    address: 192.168.43.217:2181
    protocol: zookeeper
    check: false
  consumer:
    check:  false
    timeout: 3000

